### ISSUE TITLE
fetch error

### ISSUE THREAD

**Issue by pasanmd** [evanx/geo-cache#6]
i can see below error when redis reaches maximum error limit.

FetchError: maximum redirect reached at: https://maps.googleapis.com/maps/api/place/autocomplete/json?key=xxxxxxxxxxxxxxxxxxxxxxxxxxx&input=st%20paul%20s%20girl%20s%20school%20mila&types=&components=country%3Alk&location=6.8547731%2C79.9150717&radius=500&google_abuse=GOOGLE_ABUSE_EXEMPTION%3DID%3Dbfb8707ea56c403f:TM%3D1600995694:C%3D%3E:IP%3D35.187.253.33-:S%3DAPGng0tGsdl8L0w5ocAUTgJT1fdzgrR8oA%3B+path%3D/%3B+domain%3Dgoogle.com%3B+expires%3DFri,+25-Sep-2020+04:01:34+GMT
      at ClientRequest.<anonymous> (/etc/geo-cache/geo-cache/node_modules/node-fetch/index.js:147:13)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:198:13)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at TLSSocket.Readable.push (_stream_readable.js:224:10)
      at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

could this be an issue with the google

**Comment by evanx** [comment]
`FetchError: maximum redirect` sounds like cyclic redirect of `maps.googleapis.com` - can you debug this URL using `curl -I` from the CLI?
